apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-server-schedule
  namespace: backend
  labels:
    app: nest-server-schedule
spec:
  replicas: 1                 # 根据业务量调整pod的数量
  selector:
    matchLabels:
      app: nest-server-schedule          # 修改为项目的名字
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nest-server-schedule     # 修改成项目的名字
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: pulluser
      containers:
      - image: <IMAGE>:<IMAGE_TAG>
        name: nest-server-schedule
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /deploy/ready
            port: 9090
          initialDelaySeconds: 40
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /deploy/live
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 3
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 20
        args:
        - "node"
        - "/nest-server/dist/script/schedule-demo.js"
        env:
        - name: DEPLOY_ENV
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: DEPLOY_ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: PORT
        - name: MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: MYSQL_URL
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: MONGO_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: REDIS_URL
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: REDIS_PWD
        - name: REDIS_DB
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: REDIS_DB
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: LOG_LEVEL
        - name: NO_COLOR
          valueFrom:
            secretKeyRef:
              name: cm-nest-server
              key: NO_COLOR
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
