apiVersion: v1
stringData:
  DEPLOY_ENV: 'prod'
  PORT: '9090'
  MYSQL_URL: "mysql://mysqlName:mysql123@localhost:3309/hh"
  MONGO_URL: "mongodb://root:mongo123@localhost:27019/"
  REDIS_URL: "redis://localhost:6389"
  REDIS_PWD: ""
  REDIS_DB: '3'
  REDIS_PREFIX: 'nest-server-qa'
  JWT_SECRET: 'Z6iQ9Yw2dghUEOponPmZloRQEd6CnYjw'
  INSTANCES: '2'
  LOG_LEVEL: 'info'
  NO_COLOR: '1'
kind: Secret
metadata:
  name: cm-nest-server
  namespace: backend
type: Opaque
